# Meta Data for SEO

## Homepage
title = "Lane Holloway, PhD"
titleSeparator = "-"
titleAddition = "Home Page"
description = "Home page for Lane Holloway, PhD."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "drlholloway.github.io"
titleHome = "Lane Holloway, PhD"

## Twitter Cards
#twitterSite = "@DrLHolloway"
twitterCreator = "@DrLHolloway"

## JSON-LD
# schemaType = "Person"
# schemaType = "Organization"
# schemaName = "LaneHolloway"
# schemaAuthor = "Lane Holloway, PhD"
# schemaAuthorTwitter = "https://twitter.com/DrLHolloway"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/lane-holloway-phd/"
# schemaAuthorGitHub = "https://github.com/drlholloway"
# schemaLocale = "en-US"
# schemaLogo = "logo-doks.png"
# schemaLogoWidth = 400
# schemaLogoHeight = 400
# schemaImage = "doks.png"
# schemaImageWidth = 1280
# schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/getdoks"
# schemaLinkedIn = ""
# schemaGitHub = "https://github.com/h-enk/doks"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by Hopes, Dreams, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2023 Lane Holloway"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/drlholloway/drlholloway.github.io"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
